### ISSUE TITLE
Current score on the dev set

### ISSUE THREAD

**Issue by VietHoang1512** [heinrichreimer/modern-talking#2]
Hi all, I've stepped into this competition and have some trouble in training these KP matching models. My score is stuck < 0.8, so may I ask about your current score on the dev set follow these great approaches.

**Comment by janheinrichmerker** [comment]
Which score do you mean? mAP strict or mAP relaxed?

**Comment by VietHoang1512** [comment]
sorry, i mean both of them
Vào Th 2, 21 thg 6, 2021 lúc 00:43 Jan Heinrich Reimer <
***@***.***> đã viết:

**Comment by janheinrichmerker** [comment]
Our baseline model currently does mAP strict 0.64 and mAP relaxed 0.82.
If you also have issues with the evaluation script, I've reported an issue on their GitHub: https://github.com/IBM/KPA_2021_shared_task/issues/1

**Comment by janheinrichmerker** [comment]
The best mAP score reported from a team at our university was 0.95 for both strict and relaxed.
